version: '3'
services:
  s4e-backend-e2e:
    build: ./s4e-backend
    env_file:
      - ${BACKEND_E2E_ENV_PATH:-backend-e2e.env}
    volumes:
      - ${BACKEND_E2E_JAR_PATH:-./s4e-backend/target/s4e-backend-0.0.0-SNAPSHOT.jar}:/app/app.jar
      - ${BACKEND_E2E_KEYSTORE_PATH:-./s4e-backend/dev_key.p12}:/app/dev_key.p12
    ports:
      - ${BACKEND_E2E_PORT:-4203}:4201
    networks:
      - net-test
    depends_on:
      - db-test
      - geoserver-test
      - minio-test
      - broker-test
  s4e-web-e2e:
    image: nginx:alpine
    ports:
      - ${WEB_E2E_PORT:-4202}:443
    volumes:
      - ./s4e-web/target/webapp:/usr/share/nginx/html
      - ${WEB_E2E_CONF_PATH:-./s4e-web/nginx-e2e.conf}:/etc/nginx/nginx.conf
      - ${WEB_E2E_CERTS_PATH:-./s4e-web/.angular-ssl}:/etc/nginx/certs
    networks:
      - net-test
    depends_on:
      - s4e-backend-e2e
      - minio-test
      - gs-gateway-test
  gs-gateway-test:
    build: ./gs-gateway
    env_file:
      - ${GS_GATEWAY_TEST_ENV_PATH:-gsg-test.env}
      - ${GS_GATEWAY_TEST_DATASET_ENV_PATH:-gsg-seed-1.env}
    ports:
      - ${GS_GATEWAY_TEST_PORT:-8091}:8090
    networks:
      - net-test
    depends_on:
      - geoserver-test
  minio-test:
    image: fiddev/minio-test:1.2.0
    ports:
      - ${MINIO_TEST_PORT:-9002}:9000
    networks:
      - net-test
    environment:
      MINIO_ACCESS_KEY: ${MINIO_TEST_ACCESS_KEY:-miniotest}
      MINIO_SECRET_KEY: ${MINIO_TEST_SECRET_KEY:-miniotest123}
    command: server /data
  geoserver-test:
    image: fiddev/geoserver:1.5.0-GS2.18.0
    ports:
      - ${GEOSERVER_TEST_PORT:-8081}:8080
    networks:
      - net-test
    environment:
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_TEST_ADMIN_PASSWORD:-admintest123}
      JNDI_URL: ${GEOSERVER_TEST_JNDI_URL:-jdbc:postgresql://db-test:5432/sat4envi_test}
      JNDI_USERNAME: ${GEOSERVER_TEST_JNDI_USERNAME:-sat4envi_test}
      JNDI_PASSWORD: ${GEOSERVER_TEST_JNDI_PASSWORD:-sat4envi_test}
      S3_ENDPOINT: ${GEOSERVER_S3_ENDPOINT:-http://minio-test:9000/}
      S3_ACCESS_KEY: ${GEOSERVER_S3_ACCESS_KEY:-miniotest}
      S3_SECRET_KEY: ${GEOSERVER_S3_SECRET_KEY:-miniotest123}
  db-test:
    image: postgis/postgis:13-3.0
    ports:
      - ${DB_TEST_PORT:-5434}:5432
    networks:
      - net-test
    environment:
      POSTGRES_DB: ${DB_TEST_POSTGRES_DB:-sat4envi_test}
      POSTGRES_USER: ${DB_TEST_POSTGRES_USER:-sat4envi_test}
      POSTGRES_PASSWORD: ${DB_TEST_POSTGRES_PASSWORD:-sat4envi_test}
  broker-test:
    image: rabbitmq:3.8.3-management
    ports:
      - ${BROKER_TEST_PORT:-5673}:5672
      - ${BROKER_TEST_PORT_MANAGEMENT:-15673}:15672
    networks:
      - net-test
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_TEST_USERNAME:-rabbittest}
      RABBITMQ_DEFAULT_PASS: ${BROKER_TEST_PASSWORD:-rabbittest123}

networks:
  net-test:
