server.port=8090

gateway.geoserver-uri=http://localhost:8080/
gateway.open-layers=development:108m,development:setvak,development:wv_ir

# The public key from dev_key.p12
jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp/qwGpxzLbfgkjByYMPhukSPsFysvAPDfy0/RjEiz3cZKNYmjRQU0u87Sq7HmPjQCcZTxa+FZJn1KTx/LZU261DIlOqNzxqd8GoEsKTgkQrPh4Nq3ZZkEPLqbY1YyED1jaYzHO3+jFH55BUaVE9lbO8andlWgED9SF3qQso8Sd7z3mZZqePLdEoXgKCGQa+bG10ZyMTVwrDoAPFetXuXVSRh7TC7ft/3oWZ3MTCcfCoQiWM+7ofb+rxJGawGfnF68sbxkWEnFnnD6/Z81ihvTkoI8AKvSDBPiDO2PWyrhQZ6D7L6phZdqPSXQs9JzzIn21hKsz9fySI9RFeOGGbt3QIDAQAB
