name: Test E2E

on: [push]
jobs:
  web-e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1
      - name: Cache web-e2e
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-web-e2e-${{ hashFiles('**/pom.xml', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-web-e2e-
      - name: Maven package
        run: ./mvnw clean package -DskipTests -Dsha1=-${GITHUB_SHA}
      - name: Start containers
        run: docker-compose -f docker-compose-test.yml up -d
        env:
          BACKEND_E2E_JAR_PATH: ./s4e-backend/target/s4e-backend-0.0.0-${{ github.sha }}-SNAPSHOT.jar
      - name: Seed products for E2E tests
        run: src/scripts/seed.sh http://localhost:4203 seed-configs/seed-1
        working-directory: s4e-backend
        env:
          TIMEOUT: 60
      - name: E2E tests
        run: npm run e2e
        working-directory: s4e-web
        env:
          CYPRESS_DONT_DELETE_DOWNLOADED_FILES: true
      - name: Containers logs
        if: failure()
        run: docker-compose -f docker-compose-test.yml logs
      - name: Stop s4e-backend and s4e-web
        run: docker-compose -f docker-compose-test.yml down
    # Enable after downloading files in E2E has been resolved
    #- name: E2E upload Report PDF
    #  uses: actions/upload-artifact@v2
    #  if: success()
    #  with:
    #    name: report.pdf
    #    path: /root/Downloads/RAPORT.1990-01-01T00_00_00.000Z.pdf
