name: Build & Test

on: [push]
jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Cache backend
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-backend-${{ hashFiles('pom.xml', 's4e-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-backend-
      - name: Maven package
        run: ../mvnw clean package -DskipTests
        working-directory: s4e-backend
      - name: Start containers
        run: docker-compose -f docker-compose-test.yml up -d db-test broker-test minio-test geoserver-test
      - name: Maven test and verify
        run: ../mvnw verify
        working-directory: s4e-backend
      - name: Containers logs
        if: failure()
        run: docker-compose -f docker-compose-test.yml logs
      - name: Stop containers
        run: docker-compose -f docker-compose-test.yml down

  gs-gateway:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Cache gs-gateway
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-gs-gateway-${{ hashFiles('pom.xml', 'gs-gateway/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-gs-gateway-
      - name: Maven package
        run: ../mvnw clean package -DskipTests
        working-directory: gs-gateway
      - name: Maven test
        run: ../mvnw test
        working-directory: gs-gateway

  web:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2
      - name: Cache web
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.npm
          key: ${{ runner.os }}-web-${{ hashFiles('**/pom.xml', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-web-
      - name: Maven package
        run: ../mvnw clean package -DskipTests -Dsha1=-${GITHUB_SHA}
        working-directory: s4e-web
      - name: Maven test
        run: ../mvnw test
        working-directory: s4e-web
